/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(800,450); //Escogemos el tamaño inicial
        setLocationRelativeTo(null); // Para que se inicie en medio de mi ventana
        setTitle("Proyecto Programación Javier Álvarez García");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Clientes = new javax.swing.JButton();
        Boton_Empleados = new javax.swing.JButton();
        Boton_Productos = new javax.swing.JButton();
        Boton_Direcciones = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        Boton_Stock = new javax.swing.JButton();
        Boton_Pedidos = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Clientes.setText("CLIENTES");
        Boton_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, 60));

        Boton_Empleados.setText("EMPLEADOS");
        Boton_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, 60));

        Boton_Productos.setText("PRODUCTOS");
        Boton_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ProductosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 140, 60));

        Boton_Direcciones.setText("DIRECCIONES");
        Boton_Direcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DireccionesActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Direcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 130, 60));

        Boton_Salir.setText("SALIR");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 180, 70));

        Boton_Stock.setText("STOCK");
        Boton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_StockActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, 50));

        Boton_Pedidos.setText("PEDIDOS");
        Boton_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PedidosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 140, 60));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(Menu.this, "¿Estas seguro que quieres cerrar la aplicación?",
                "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ClientesActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaClientes vista = new VistaClientes();
            vista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Boton_ClientesActionPerformed

    private void Boton_DireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DireccionesActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaDirecciones vista = new VistaDirecciones();
            vista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Boton_DireccionesActionPerformed

    private void Boton_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EmpleadosActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaEmpleados vista = new VistaEmpleados();
            vista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Boton_EmpleadosActionPerformed

    private void Boton_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PedidosActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaPedidos vista = new VistaPedidos();
            vista.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_Boton_PedidosActionPerformed

    private void Boton_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ProductosActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaProductos vista = new VistaProductos();
            vista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Boton_ProductosActionPerformed

    private void Boton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_StockActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "Estás seguro de cambiar de página?", "Cambio de ventana", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            VistaStock vista = new VistaStock();
            vista.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_Boton_StockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Clientes;
    private javax.swing.JButton Boton_Direcciones;
    private javax.swing.JButton Boton_Empleados;
    private javax.swing.JButton Boton_Pedidos;
    private javax.swing.JButton Boton_Productos;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_Stock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
