/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Empleados;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaEmpleados extends javax.swing.JFrame {
protected Connection conexion;
    String URL = "jdbc:mysql://localhost:3306/proyectofinaljavieralvarez";
    String usuario = "root";
    String contraseña = "1234";
    PreparedStatement ps; //Da datos
    ResultSet rs; //Obtiiene datos

    public Connection getConnection() {  //Esto hay que ponserlo siempre

        try {
            
            conexion = (Connection) DriverManager.getConnection(URL, usuario, contraseña);
            //JOptionPane.showMessageDialog(null,"Conexión a la base de datos establecida con éxito ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);

        }
        return conexion;
    }
    /**
     * Creates new form VistaEmpleados
     */
    public VistaEmpleados() {
        initComponents();
        setSize(830,580); //Escogemos el tamaño inicial
        setLocationRelativeTo(null); // Para que se inicie en medio de mi ventana
        setTitle("Proyecto Programación Javier Álvarez García");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_IDEmpleado = new javax.swing.JLabel();
        Caja_IDEmpleado = new javax.swing.JTextField();
        Label_NumeroDeVentas = new javax.swing.JLabel();
        Caja_NumeroDeVentas = new javax.swing.JTextField();
        Label_Nombre = new javax.swing.JLabel();
        Caja_Nombre = new javax.swing.JTextField();
        LabelApellidos = new javax.swing.JLabel();
        Caja_Apellidos = new javax.swing.JTextField();
        Label_Telefono = new javax.swing.JLabel();
        Caja_Teléfono = new javax.swing.JTextField();
        Label_DNI = new javax.swing.JLabel();
        Caja_DNI = new javax.swing.JTextField();
        Caja_Nacionalidad = new javax.swing.JTextField();
        Caja_HorasTrabajadas = new javax.swing.JTextField();
        Caja_SueldoMensual = new javax.swing.JTextField();
        Caja_FechaDeNacimiento = new javax.swing.JTextField();
        Label_Nacionalidad = new javax.swing.JLabel();
        Label_HorasTrabajadas = new javax.swing.JLabel();
        Label_SueldoMensual = new javax.swing.JLabel();
        Label_FechaDeNacimiento = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        Boton_buscar = new javax.swing.JButton();
        Boton_Insertar = new javax.swing.JButton();
        Boton_Modificar = new javax.swing.JButton();
        Boton_Eliminar = new javax.swing.JButton();
        Boton_Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Caja_SueldoAnual = new javax.swing.JTextField();
        Boton_MenuPrincipal = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_IDEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_IDEmpleado.setText("IDEmpleado:");
        jPanel1.add(Label_IDEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));
        jPanel1.add(Caja_IDEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 30));

        Label_NumeroDeVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_NumeroDeVentas.setText("Numero de ventas: ");
        jPanel1.add(Label_NumeroDeVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));
        jPanel1.add(Caja_NumeroDeVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 210, 30));

        Label_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Nombre.setText("Nombre: ");
        jPanel1.add(Label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));
        jPanel1.add(Caja_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 210, 40));

        LabelApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelApellidos.setText("Apellidos:");
        jPanel1.add(LabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));
        jPanel1.add(Caja_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 40));

        Label_Telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Telefono.setText("Teléfono: ");
        jPanel1.add(Label_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));
        jPanel1.add(Caja_Teléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 210, 30));

        Label_DNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_DNI.setText("DNI: ");
        jPanel1.add(Label_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));
        jPanel1.add(Caja_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 210, 30));
        jPanel1.add(Caja_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 30));
        jPanel1.add(Caja_HorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 210, 40));
        jPanel1.add(Caja_SueldoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 210, 40));

        Caja_FechaDeNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(Caja_FechaDeNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 210, 50));

        Label_Nacionalidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Nacionalidad.setText("Nacionalidad: ");
        jPanel1.add(Label_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, -1));

        Label_HorasTrabajadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_HorasTrabajadas.setText("Horas trabajadas: ");
        jPanel1.add(Label_HorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        Label_SueldoMensual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_SueldoMensual.setText("Sueldo mensual: ");
        jPanel1.add(Label_SueldoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, -1));

        Label_FechaDeNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_FechaDeNacimiento.setText("Fecha de nacimiento: ");
        jPanel1.add(Label_FechaDeNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, -1));
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 50));

        Boton_buscar.setText("BUSCAR");
        jPanel1.add(Boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 180, 50));

        Boton_Insertar.setText("INSERTAR");
        Boton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_InsertarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 180, 40));

        Boton_Modificar.setText("MODIFICAR");
        Boton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 180, 40));

        Boton_Eliminar.setText("ELIMINAR");
        Boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 180, 40));

        Boton_Limpiar.setText("LIMPIAR");
        Boton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sueldo Anual: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, -1));
        jPanel1.add(Caja_SueldoAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 210, 40));

        Boton_MenuPrincipal.setText("MENU PRINCIPAL");
        jPanel1.add(Boton_MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 180, 40));

        Boton_Salir.setText("SALIR");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 180, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Recuerda buscar por ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        Fondo.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -130, 1020, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_InsertarActionPerformed
        Connection conexion = getConnection();

        try {//Establecemos la llamada a la base de datos
            ps = conexion.prepareStatement("INSERT INTO Empleados(IDEmpleado,NumeroDeVentas,Nombre,Apellidos,Telefono,DNI,Nacionalidad,HorasTrabajadas,SueldoMensual,SueldoAnual,FechaNacimiento) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
            //Insertamos los datos

            ps.setInt(1, Integer.parseInt(Caja_IDEmpleado.getText())); //En el primer ?, introduces...
            ps.setInt(2, Integer.parseInt(Caja_NumeroDeVentas.getText()));
            ps.setString(3, Caja_Nombre.getText());
            ps.setString(4, Caja_Apellidos.getText());
            ps.setString(5, Caja_Teléfono.getText());
            ps.setString(6, Caja_DNI.getText());
            ps.setString(7, Caja_Nacionalidad.getText());
            ps.setInt(8, Integer.parseInt(Caja_HorasTrabajadas.getText()));
            ps.setInt(9, Integer.parseInt(Caja_SueldoMensual.getText()));
            ps.setInt(10, Integer.parseInt(Caja_SueldoAnual.getText()));
            ps.setDate(11, Date.valueOf(Caja_FechaDeNacimiento.getText()));
            //Como queremos realizar una inserción, queremos actualizar la bd
            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Inserción realizada con éxito en la base de datos");
            } 
        } catch (Exception ex) {
            System.err.println("Error, no se han insertado los datos correctamente."+ex);
           
        } finally { //El finally siempre se ejecutará, por lo que finalizaríamos siempre la conexión
            try {
                conexion.close();
            } catch (Exception e) {
                System.err.println("Error, " + e);
            }
        }
    }//GEN-LAST:event_Boton_InsertarActionPerformed
        
    //Vamos a crear un método que limpie las cajas
    public void limpiarCajas(){
        Caja_Apellidos.setText("");
        Caja_DNI.setText("");
        Caja_FechaDeNacimiento.setText("");
        Caja_HorasTrabajadas.setText("");
        Caja_IDEmpleado.setText("");
        Caja_Nacionalidad.setText("");
        Caja_Nombre.setText("");
        Caja_NumeroDeVentas.setText("");
        Caja_SueldoAnual.setText("");
        Caja_SueldoMensual.setText("");
        Caja_Teléfono.setText("");
    }
    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
                int opcion = JOptionPane.showConfirmDialog(VistaEmpleados.this, "¿Estas seguro que quieres cerrar la aplicación?",
                "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_LimpiarActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_Boton_LimpiarActionPerformed

    private void Boton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ModificarActionPerformed
        Connection conexion = getConnection();

        try {//Establecemos la llamada a la base de datos
            ps = conexion.prepareStatement("UPDATE Empleados SET NumeroDeVentas=?, Nombre=?, Apellidos=?, Telefono=?, DNI=?, Nacionalidad=?, HorasTrabajadas=?, SueldoMensual=?, SueldoAnual=?, FechaNacimiento=? WHERE IDEmpleado=?");
            //Insertamos los datos

            ps.setInt(11, Integer.parseInt(Caja_IDEmpleado.getText())); //En el primer ?, introduces...
            ps.setInt(1, Integer.parseInt(Caja_NumeroDeVentas.getText()));
            ps.setString(2, Caja_Nombre.getText());
            ps.setString(3, Caja_Apellidos.getText());
            ps.setString(4, Caja_Teléfono.getText());
            ps.setString(5, Caja_DNI.getText());
            ps.setString(6, Caja_Nacionalidad.getText());
            ps.setInt(7, Integer.parseInt(Caja_HorasTrabajadas.getText()));
            ps.setInt(8, Integer.parseInt(Caja_SueldoMensual.getText()));
            ps.setInt(9, Integer.parseInt(Caja_SueldoAnual.getText()));
            ps.setDate(10, Date.valueOf(Caja_FechaDeNacimiento.getText()));
            //Como queremos realizar una inserción, queremos actualizar la bd
            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Modificación realizada con éxito en la base de datos");
            } 
        } catch (Exception ex) {
            System.err.println("Error, no se han insertado los datos correctamente."+ex);
           
        } finally { //El finally siempre se ejecutará, por lo que finalizaríamos siempre la conexión
            try {
                conexion.close();
            } catch (Exception e) {
                System.err.println("Error, " + e);
            }
        }
    }//GEN-LAST:event_Boton_ModificarActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        Connection conexion = getConnection();

        try {//Establecemos la llamada a la base de datos
            ps = conexion.prepareStatement("DELETE FROM Empleados WHERE IDEmpleado = ?; ");

            ps.setInt(1, Integer.parseInt(Caja_IDEmpleado.getText())); //En el primer ?, introduces...
            //Como queremos realizar una inserción, queremos actualizar la bd
            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Modificación realizada con éxito en la base de datos");
            } 
        } catch (Exception ex) {
            System.err.println("Error, no se han insertado los datos correctamente."+ex);
           
        } finally { //El finally siempre se ejecutará, por lo que finalizaríamos siempre la conexión
            try {
                conexion.close();
            } catch (Exception e) {
                System.err.println("Error, " + e);
            }
        }
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_Eliminar;
    public javax.swing.JButton Boton_Insertar;
    public javax.swing.JButton Boton_Limpiar;
    private javax.swing.JButton Boton_MenuPrincipal;
    public javax.swing.JButton Boton_Modificar;
    private javax.swing.JButton Boton_Salir;
    public javax.swing.JButton Boton_buscar;
    public javax.swing.JTextField Buscar;
    public javax.swing.JTextField Caja_Apellidos;
    public javax.swing.JTextField Caja_DNI;
    public javax.swing.JTextField Caja_FechaDeNacimiento;
    public javax.swing.JTextField Caja_HorasTrabajadas;
    public javax.swing.JTextField Caja_IDEmpleado;
    public javax.swing.JTextField Caja_Nacionalidad;
    public javax.swing.JTextField Caja_Nombre;
    public javax.swing.JTextField Caja_NumeroDeVentas;
    public javax.swing.JTextField Caja_SueldoAnual;
    public javax.swing.JTextField Caja_SueldoMensual;
    public javax.swing.JTextField Caja_Teléfono;
    public javax.swing.JTextField Fondo;
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel Label_DNI;
    private javax.swing.JLabel Label_FechaDeNacimiento;
    private javax.swing.JLabel Label_HorasTrabajadas;
    private javax.swing.JLabel Label_IDEmpleado;
    private javax.swing.JLabel Label_Nacionalidad;
    private javax.swing.JLabel Label_Nombre;
    private javax.swing.JLabel Label_NumeroDeVentas;
    private javax.swing.JLabel Label_SueldoMensual;
    private javax.swing.JLabel Label_Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
